Ported mainline binutils-config to prefix-glibc.

diff --git a/overlay/sys-devel/binutils-config/files/binutils-config-3 b/overlay/sys-devel/binutils-config/files/binutils-config-3
--- a/overlay/sys-devel/binutils-config/files/binutils-config-3
+++ b/overlay/sys-devel/binutils-config/files/binutils-config-3
@@ -1,23 +1,26 @@
-#!/bin/bash
+#!@GENTOO_PORTAGE_EPREFIX@/bin/bash
 # Copyright 1999-2012 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /var/cvsroot/gentoo-x86/sys-devel/binutils-config/files/binutils-config-3,v 1.10 2012/11/18 07:54:46 vapier Exp $
+# $Header: /var/cvsroot/gentoo-x86/sys-devel/binutils-config/files/binutils-config-3,v 1.9 2012/08/18 03:57:50 vapier Exp $
 
 # Format of /etc/env.d/binutils/:
 #  config-TARGET:	CURRENT=version for TARGET
 #  TARGET-VER:		has a TARGET and VER variable
 
+EPREFIX="@GENTOO_PORTAGE_EPREFIX@"
+
 : ${ROOT:=/}
 [[ ${ROOT} != */ ]] && ROOT="${ROOT}/"
 [[ ${ROOT} != /* ]] && ROOT="${PWD%/}/${ROOT}"
+EROOT="${ROOT%/}${EPREFIX}/"
 
-cd /
+cd ${EPREFIX}
 
 trap ":" INT QUIT TSTP
 
 argv0=${0##*/}
-source /etc/init.d/functions.sh || {
-	echo "${argv0}: Could not source /etc/init.d/functions.sh!" 1>&2
+source ${EPREFIX}/etc/init.d/functions.sh || {
+	echo "${argv0}: Could not source ${EPREFIX}/etc/init.d/functions.sh!" 1>&2
 	exit 1
 }
 esyslog() { :; }
@@ -123,7 +126,7 @@ setup_env() {
 		# Newer paths: /usr/${HOST}/${TARGET}/...
 		# Older paths: /usr/${TARGET}/...
 		#
-		if [[ -d ${ROOT}/usr/${HOST}/${TARGET}/binutils-bin/${VER} ]] ; then
+		if [[ -d ${EROOT}/usr/${HOST}/${TARGET}/binutils-bin/${VER} ]] ; then
 			BINPATH=/usr/${HOST}/${TARGET}/binutils-bin/${VER}
 			BINPATH_LINKS=/usr/libexec/gcc/${TARGET}
 		fi
@@ -139,17 +142,17 @@ switch_profile() {
 
 	setup_env || return 1
 
-	cd "${ROOT}/${BINPATH}" || exit 1
-	mkdir -p "${ROOT}/${BINPATH_LINKS}" "${ROOT}/usr/bin"
+	cd "${EROOT}/${BINPATH}" || exit 1
+	mkdir -p "${EROOT}/${BINPATH_LINKS}" "${EROOT}/usr/bin"
 	for x in * ; do
-		atomic_ln "${BINPATH}/${x}" "${ROOT}/${BINPATH_LINKS}" "${x}"
-		atomic_ln "${BINPATH_LINKS}/${x}" "${ROOT}/usr/bin/" "${TARGET}-${x}"
+		atomic_ln "${EROOT}/${BINPATH}/${x}" "${EROOT}/${BINPATH_LINKS}" "${x}"
+		atomic_ln "${EROOT}/${BINPATH_LINKS}/${x}" "${EROOT}/usr/bin/" "${TARGET}-${x}"
 		for fake in ${FAKE_TARGETS} ; do
 			[[ -f ${ENV_D}/config-${fake} ]] && continue
-			atomic_ln "${BINPATH_LINKS}/${x}" "${ROOT}/usr/bin" "${fake}-${x}"
+			atomic_ln "${EROOT}/${BINPATH_LINKS}/${x}" "${EROOT}/usr/bin" "${fake}-${x}"
 		done
 		if [[ ${TARGET} == ${HOST} ]] ; then
-			atomic_ln "${TARGET}-${x}" "${ROOT}/usr/bin" "${x}"
+			atomic_ln "${TARGET}-${x}" "${EROOT}/usr/bin" "${x}"
 		fi
 	done
 
@@ -157,38 +160,43 @@ switch_profile() {
 	# Generate library / ldscripts symlinks
 	#
 	: ${LIBPATH:=/usr/lib/binutils/${TARGET}/${VER}}
-	cd "${ROOT}/${LIBPATH}" || exit 1
+	[[ ${LIBPATH} == ${EPREFIX}* ]] && LIBPATH=${LIBPATH#${EPREFIX}}
 	if [[ ${TARGET} == ${HOST} ]] ; then
-		dstlib=${ROOT}/usr/${HOST}/lib
+		dstlib=${EROOT}/usr/${HOST}/lib
 	else
-		dstlib=${ROOT}/usr/${HOST}/${TARGET}/lib
+		dstlib=${EROOT}/usr/${HOST}/${TARGET}/lib
 	fi
 	# When upgrading, we need to clean up ldscripts and libs
 	mkdir -p "${dstlib}"
-	rm -rf "${ROOT}/${BINPATH_LINKS}"/ldscripts
-	atomic_ln "${LIBPATH}/ldscripts" "${dstlib}" "ldscripts"
-	find -L "${dstlib}" -type l -exec rm -v {} +
+	rm -rf "${EROOT}/${BINPATH_LINKS}"/ldscripts
+	# avoid pointless warning about removing non-existant ldscripts dir
+	if [[ -d ${EROOT}/${LIBPATH}/ldscripts ]] ; then
+		atomic_ln "${EROOT}/${LIBPATH}/ldscripts" "${dstlib}" "ldscripts"
+		find -L "${dstlib}" -type l -exec rm -v {} +
+	fi
 	for x in lib* ; do
-		atomic_ln "${LIBPATH}/${x}" "${dstlib}" "${x}"
+		# avoid symlink 'lib*' -> '/...' when no libs (native/nongnu binutils)
+		[[ ${x} != 'lib*' ]] || continue
+		atomic_ln "${EROOT}/${LIBPATH}/${x}" "${dstlib}" "${x}"
 	done
 
 	#
 	# Generate include symlinks
 	#
 	INCPATH=${LIBPATH}/include
-	if [[ -d ${ROOT}/${INCPATH} ]] ; then
-		cd "${ROOT}/${INCPATH}" || exit 1
+	if [[ -d ${EROOT}/${INCPATH} ]] ; then
+		cd "${EROOT}/${INCPATH}" || exit 1
 		if [[ ${HOST} == ${TARGET} ]] ; then
-			mkdir -p "${ROOT}/usr/include"
+			mkdir -p "${EROOT}/usr/include"
 			for x in * ; do
-				atomic_ln "${INCPATH}/${x}" "${ROOT}/usr/include" "${x}"
+				atomic_ln "${EROOT}/${INCPATH}/${x}" "${EROOT}/usr/include" "${x}"
 			done
 		else
 			# Clean out old path -- cannot use '-exec {} +' syntax here
-			find . -type f -exec rm -f "${ROOT}/usr/${TARGET}/usr/include/{}" \;
-			rmdir "${ROOT}/usr/${TARGET}/usr/include" >& /dev/null
-			rmdir "${ROOT}/usr/${TARGET}/usr" >& /dev/null
-			rmdir "${ROOT}/usr/${TARGET}" >& /dev/null
+			find . -type f -exec rm -f "${EROOT}/usr/${TARGET}/usr/include/{}" \;
+			rmdir "${EROOT}/usr/${TARGET}/usr/include" >& /dev/null
+			rmdir "${EROOT}/usr/${TARGET}/usr" >& /dev/null
+			rmdir "${EROOT}/usr/${TARGET}" >& /dev/null
 		fi
 	fi
 
@@ -197,14 +205,14 @@ switch_profile() {
 	#
 	if [[ ${TARGET} == ${HOST} ]] ; then
 		DATAPATH=/usr/share/binutils-data/${TARGET}/${VER}
-		local e="${ROOT}"/etc/env.d/05binutils
+		local e="${EROOT}"/etc/env.d/05binutils
 		local ee="${e}.tmp"
 		rm -f "${ee}"
 		[[ -d ${DATAPATH}/man  ]] && echo "MANPATH=${DATAPATH}/man"   >> "${ee}"
 		[[ -d ${DATAPATH}/info ]] && echo "INFOPATH=${DATAPATH}/info" >> "${ee}"
 		# hmm, `ld` has this in SEARCH_DIR(), but ld.so does not ...
-		if [[ -d ${ROOT}/etc/ld.so.conf.d ]] ; then
-			local l="${ROOT}"/etc/ld.so.conf.d/05binutils.conf
+		if [[ -d ${EROOT}/etc/ld.so.conf.d ]] ; then
+			local l="${EROOT}"/etc/ld.so.conf.d/05binutils.conf
 			local ll="${l}.tmp"
 			echo "/usr/${TARGET}/lib" > "${ll}"
 			mv_if_diff "${ll}" "${l}"
@@ -254,36 +262,33 @@ uninstall_target() {
 		die "no profiles exist for '${TARGET}'"
 	fi
 
-	rm -f "${ENV_D}"/config-${TARGET} "${ROOT}"/etc/ld.so.conf.d/05binutils.conf
+	rm -f "${ENV_D}"/config-${TARGET} "${EROOT}"/etc/ld.so.conf.d/05binutils.conf
 
 	# XXX: we still leave behind FAKE_TARGETS in /usr/bin ...
 	local x
-	for x in \
-		addr2line ar as c++filt elf2flt elfedit flthdr gprof \
-		ld ld.{bfd,gold,real} \
-		nm objcopy objdump ranlib readelf size strings strip
-	do
+	for x in addr2line ar as c++filt elf2flt flthdr gprof ld ld.real \
+	         nm objcopy objdump ranlib readelf size strings strip ; do
 		x=(
-			"${ROOT}"/usr/bin/${TARGET}-${x}
-			"${ROOT}"/usr/{${HOST}/,}${TARGET}/bin/${x}
-			"${ROOT}"/usr/libexec/gcc/${TARGET}/${x}
+			"${EROOT}"/usr/bin/${TARGET}-${x}
+			"${EROOT}"/usr/{${HOST}/,}${TARGET}/bin/${x}
+			"${EROOT}"/usr/libexec/gcc/${TARGET}/${x}
 		)
 		rm -f "${x[@]}"
 	done
 	for x in ansidecl.h bfd.h bfdlink.h dis-asm.h symcat.h ; do
-		rm -f "${ROOT}"/usr/{${HOST}/,}${TARGET}/{usr/,}include/${x}
+		rm -f "${EROOT}"/usr/{${HOST}/,}${TARGET}/{usr/,}include/${x}
 	done
 	for x in bfd iberty opcodes ; do
-		rm -f "${ROOT}"/usr/${HOST}/${TARGET}/lib/lib${x}{{-*,}.so,.a,.la}
+		rm -f "${EROOT}"/usr/${HOST}/${TARGET}/lib/lib${x}{{-*,}.so,.a,.la}
 	done
 	# Delete broken symlinks
-	local destdir="${ROOT}/usr/${HOST}/${TARGET}"
+	local destdir="${EROOT}/usr/${HOST}/${TARGET}"
 	rm -f "${destdir}"/lib/ldscripts
 	find -L "${destdir}"/lib -type l -exec rm {} +
 	rmdir \
 		"${destdir}"/{bin,include,lib,usr} \
 		"${destdir}" \
-		"${ROOT}"/var/db/pkg/cross-${TARGET} \
+		"${EROOT}"/var/db/pkg/cross-${TARGET} \
 		2>/dev/null
 
 	rm -f "${ENV_D}"/${TARGET}-*
@@ -364,7 +369,7 @@ switch_linker() {
 	esac
 
 	setup_env || return 1
-	bpath="${ROOT}/${BINPATH}"
+	bpath="${EROOT}/${BINPATH}"
 
 	# does this binutils even support the requested linker ?
 	if [[ ! -e ${bpath}/${ld} ]] ; then
@@ -382,7 +387,7 @@ set_HOST() {
 	: ${HOST:=${CHOST:-$(portageq envvar CHOST)}}
 }
 
-ENV_D="${ROOT}etc/env.d/binutils"
+ENV_D="${EROOT}etc/env.d/binutils"
 
 DEBUG="no"
 NEED_ACTION="yes"
